grpc:
  server:
    port: 0

spring:
  kafka:
    producer:
      properties:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: ru.practicum.ewm.serializer.AvroSerializer

collector:
  topic:
    user-action: stats.user-actions.v1