grpc:
  server:
    port: 0

spring:
  kafka:
    bootstrap-server: localhost:9092

    consumer:
      user-action-client-id: UserActionClient
      user-action-group-id: UserActionGroup
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: ru.practicum.deserializer.UserActionDeserializer
      enable-auto-commit: false
      poll-timeout: 1000
      similarity-client-id: SimilarityClient
      similarity-group-id: SimilarityGroup
      similarity-deserializer: ru.practicum.deserializer.EventSimilarityDeserializer

analyzer:
  topic:
    user-action: stats.user-actions.v1
    events-similarity: stats.events-similarity.v1

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show_sql: false

  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/analyzer-db
    username: analyzer
    password: analyzer

application:
  action-weight:
    view: 0.4
    register: 0.8
    like: 1.0